name: 'Dependency Review'
on:
  pull_request:

concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v7
      - name: Dependency Review
        # Testing https://github.com/actions/dependency-review-action fork with license case normalization
        uses: cadivus/dependency-review-action@7e0d3626c2819033c9491ef46fe4e4cb52b6a5e6 # normalize-license-case-dist
        with:
          config-file: './.github/dependency-review-config.yml'
